### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by sdieedu** [Kenny0521666/ScienceReadingPDFDownloader#1]
据我所知，那个网站猿猴们超级勤奋和堵死漏洞的。麻烦加密py或者混淆所有代码
否则死的飞快。。。。

**Comment by Kenny0521666** [comment]
加密完毕，谢谢提醒

**Comment by MarsJu** [comment]
![image](https://user-images.githubusercontent.com/61338247/223014080-96a13fa9-1a2a-46dc-be49-7fdce95877c4.png)

**Comment by MarsJu** [comment]
请问一下这是啥原因，运行不了。
